services:
  task:
    build: .
    restart: always
    expose:
      - 8000
    networks:
      - net
    environment:
      - FLAG=${FLAG}
    labels:
      - owl.proxy=true
      - owl.proxy.port=8000
      - owl.label.conntype=http
    mem_limit: 200M
    cpus: 0.5


networks:
  net:
    external:
      name: ctfd_frp_containers